"""
build_web.py — produce the static frontend Vercel deploys.

dashboard.html is a single self-contained file with no build step, which is
exactly what a static host wants. The only thing it cannot know on its own is
where the backend lives, so this copies it to web/index.html and bakes in the
API base as `window.__API_BASE__`.

    python build_web.py --api https://dalal-desk.fly.dev

The baked value is only a default. A visitor can still override it with
`?api=https://...`, which the page then remembers in localStorage — useful for
pointing the same deployment at a local backend while testing.

Every page gets the same treatment. ipo_page.html is served by Flask at
/ipo-desk, so it is written as web/ipo-desk.html — with `cleanUrls` set in
vercel.json that answers to the same /ipo-desk path, and the dashboard's link
works unchanged whether Flask or Vercel is serving it. A page left out of this
list would 404 on the deployed frontend while working perfectly in local dev.

Run this whenever a page changes; Vercel serves whatever is in web/.
"""

from __future__ import annotations

import argparse
import json
import os
import re

import page_render

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "web")
MARKER = "<!-- build_web.py: api base -->"

# source page -> file written into web/. The output names are what the Flask
# routes already use, so one URL works in both places.
PAGES = [
    ("dashboard.html", "index.html"),
    ("ipo_page.html", "ipo-desk.html"),
    ("intraday_page.html", "intraday-desk.html"),
    ("quality_page.html", "quality-desk.html"),
]


def build_page(source: str, out_name: str, api_base: str) -> str:
    # the shared head/JS are inlined here exactly as Flask inlines them, so
    # the served page and the built page cannot drift apart
    html = page_render.render_file(os.path.join(HERE, source))

    # JSON-escape so a stray quote in the URL cannot break out of the string
    literal = json.dumps(api_base, ensure_ascii=True).replace("<", "\\u003c")

    # The generated block is delimited by MARKER rather than matched on the
    # variable name. dashboard.html legitimately *reads* window.__API_BASE__
    # in its own script, so keying off the bare name would find that reference,
    # conclude the block already existed, and inject nothing.
    inject = (
        f"{MARKER}\n"
        "<script>\n"
        "  /* Generated by build_web.py — the backend this build points at.\n"
        "     Override per-visit with ?api=https://... */\n"
        f'  window.__API_BASE__ = {literal};\n'
        "</script>\n"
    )

    if MARKER in html:
        html = re.sub(re.escape(MARKER) + r".*?</script>\s*", lambda _: inject, html,
                      count=1, flags=re.S)
    else:
        html = html.replace("</head>", inject + "</head>", 1)

    os.makedirs(OUT_DIR, exist_ok=True)
    out_file = os.path.join(OUT_DIR, out_name)
    with open(out_file, "w", encoding="utf-8") as fh:
        fh.write(html)
    return out_file


def build(api_base: str) -> list:
    api_base = (api_base or "").strip().rstrip("/")
    if api_base and not api_base.startswith(("http://", "https://")):
        raise SystemExit(f"--api must be an absolute URL, got {api_base!r}")
    return [build_page(source, out_name, api_base) for source, out_name in PAGES]


def main(argv=None):
    parser = argparse.ArgumentParser(description="Build the static frontend")
    parser.add_argument("--api", default=os.environ.get("API_BASE", ""),
                        help="backend base URL, e.g. https://dalal-desk.fly.dev")
    args = parser.parse_args(argv)

    for out in build(args.api):
        size = os.path.getsize(out) / 1024
        print(f"wrote {out}  ({size:.0f} KB)")
    if args.api:
        print(f"points at {args.api.rstrip('/')}")
        print("\nremember: that backend needs ALLOWED_ORIGINS set to your Vercel URL,")
        print("or the browser will block every request as a CORS failure.")
    else:
        print("no --api given: the page will call the same origin it is served from,")
        print("which only works if Flask is serving it. Pass --api for a Vercel deploy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
